// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Debug environment variables (only log once)
if (!window.supabaseDebugLogged) {
  console.log('Supabase URL:', SUPABASE_URL);
  console.log('Supabase Key:', SUPABASE_PUBLISHABLE_KEY?.slice(0, 10) + '...');
  window.supabaseDebugLogged = true;
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Debug: Test Supabase connection (only log once)
if (!window.supabaseClientDebugLogged) {
  console.log('Supabase client created:', !!supabase);
  window.supabaseClientDebugLogged = true;
}